[package]
name = "chip8"
version = "0.1.0"
authors = ["Julio <julio.olvr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
log = "0.4.14"
env_logger = "0.8.3"
console_engine = "1.4.2"
